#!/bin/bash

set -e

# Copyright (c) 2014-2016, djcj <djcj@gmx.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

LANG=C
LANGUAGE=C
LC_ALL=C

appversion="17.05.19.1"

appname=$(basename "$0")
scriptpath="$(dirname "$(readlink -f "$0")")"
wdconf="$HOME/.config/UnityEngie2deb/workingdir"

errorExit() {
  echo "error: $1"
  exit 1
}

help() {
cat << EOF

 Create Debian packages of Unity engine games

 Usage:
   $appname -h | --help | -V | --version
   $appname -p | prepare <gamedir> [OPTIONS]
   $appname -b | build | make [OPTIONS]
   $appname -c | clean [OPTIONS]

 Options:
   -h, --help           print this message
   -V, --version        display version info and quit

   -p, prepare <path>   copy files from <path> and prepare a Debian
                           source package
   -b, build, make      build binary packages
   -c, clean            delete the working tree

   -o=<path>,
   --output=<path>      save Debian packages in <path>
   --working-dir=<path> Working directory where the temporary files are stored.

   -d, --data           build a separate package for architecture-
                           independent files
   --gzip               use gzip instead of xz compression (faster compression
                           at the cost of bigger packages)
   --icon=<icon>        use this icon for the desktop entry
   --no-x86             don't build an i386 package
   --no-x86_64          don't build an amd64 package
   --no-patchelf        don't remove unused DT_NEEDED entries from ELF binary
                           file headers

 Environment variables:
   UPSTREAMNAME         the original name of the game, including special chars
                           or spaces
   PKGNAME              specify a name for the executable and the package
   SHORTDESCRIPTION     a brief game description for the package and menu entry
   VERSION              the game's upstream version
   MAINTAINER           The package maintainer. Make sure to use the following
                           pattern: John Doe <nick@domain.org>
   HOMEPAGE             homepage of the game or the developer
   YEAR                 the year when the game was released
   COPYRIGHT            Who's holding the copyright?

EOF

if [ -f "$wdconf" ]; then
  lastwd="$(cat "$wdconf")"
  if [ -d "$lastwd" ]; then
    echo "Current working directory is \`$lastwd'"
  fi
fi
}

case x"$1" in
  x|x--help|x-help|x-h|x-\?)
    help;;
  x-V|x-v|x--version|x-version)
    echo $appversion; exit 0;;
esac

if [ -d "$scriptpath/templates" ] ; then
  templates="$scriptpath/templates"
elif [ -d "$scriptpath/../share/$appname" ] ; then
  templates="$scriptpath/../share/$appname"
elif [ -d "/usr/local/share/$appname" ] ; then
  templates="/usr/local/share/$appname"
elif [ -d "/usr/share/$appname" ] ; then
  templates="/usr/share/$appname"
else
  errorExit "Can't find the templates!"
fi


datapackage="no"
icon=""
mode="empty"
output="$HOME"
compression="xz"
disable_x86="no"
disable_x86_64="no"
patchelf="yes"
wd=""
for opt; do
  optarg="${opt#*=}"
  case "$opt" in
    "prepare"|"-p")
      mode="prepare"
      ;;
    "build"|"-b"|"make")
      mode="build"
      ;;
    "clean"|"-c")
      mode="clean"
      ;;
    --output=*|-o=*)
      output="$optarg"
      ;;
    --working-dir=*)
      wd="$optarg"
      ;;
    "--data"|"-d")
      datapackage="yes"
      ;;
    --gzip)
      compression="gzip"
      ;;
    --icon=*)
      icon="$optarg"
      ;;
    "--no-x86")
      disable_x86="yes"
      ;;
    "--no-x86_64")
      disable_x86_64="yes"
      ;;
    "--no-patchelf")
      patchelf="no"
      ;;
    "--help"|"-h"|"--version"|"-V")
      ;;
    *)
      origpath="$optarg"
      ;;
  esac
done

if [ $disable_x86 = "yes" ] && [ $disable_x86_64 = "yes" ] ; then
  errorExit "you can't use \`--no-x86' together with \`--no-x86_64'"
fi

if [ $mode = "empty" ] ; then
  help
  exit 1
fi

mkdir -p "$(dirname "$wdconf")"
touch "$wdconf"
lastwd="$(cat "$wdconf")"
if ([ $mode = "build" ] || [ $mode = "clean" ]) && [ -d "$lastwd" ] && [ -z "$wd" ] ; then
  wd="$lastwd"
fi
[ -n "$wd" ] && topsrc="$wd" || topsrc="`mktemp -d /tmp/UnityEngine2deb_tmpXXXXXXXXXX`"
echo "$topsrc" > "$wdconf"
builddir="$topsrc/build"
sourcedir="$topsrc/source"
icondir="$builddir/icon"
debian="$builddir/x86/debian"



################## clean ##################
if [ $mode = "clean" ] ; then
  rm -rvf "$topsrc" "$wdconf"
  exit 0
fi


################# prepare #################
if [ $mode = "prepare" ] ; then
  if [ -z "$origpath" ] ; then
    errorExit "no path specified"
  elif [ ! -e "$origpath" ] ; then
    errorExit "path to '$origpath' doesn't exist"
  elif [ ! -d "$origpath" ] ; then
    errorExit "'$origpath' is not a directory"
  else
    path="$( cd "$origpath" && pwd )"
  fi
  rm -rf $cleanfiles

  # get the application name
  filename="$(basename "$(find "$origpath" -type d -name *_Data)" | head -c-6)"
  [ -z "$PKGNAME" ] && name="$filename" || name="$PKGNAME"
  [ -z "$UPSTREAMNAME" ] && UPSTREAMNAME="$name"
  if [ -n "$UPSTREAMNAME" ] && [ -n "$PKGNAME" ] ; then
    name="$PKGNAME"
  fi

  # check for architectures
  x86="no"
  x86_64="no"
  rename_to_x86="no"
  rename_to_x86_64="no"
  [ -f "$origpath/$filename".x86 ] && x86="yes"
  [ -f "$origpath/$filename".x86_64 ] && x86_64="yes"
  if [ $x86 = "no" ] && [ $x86_64 = "no" ] ; then
    echo "neither '$filename.x86' nor '$filename.x86_64' found"
    if [ -f "$origpath/$filename" ] ; then
      if [ "$(file "$origpath/$filename" | grep 'ELF 32-bit')" ]; then
        echo "'$filename' (x86) found"
        x86="yes"
        rename_to_x86="yes"
      elif [ "$(file "$origpath/$filename" | grep 'ELF 64-bit')" ]; then
        echo "'$filename' (x86_64) found"
        x86_64="yes"
        rename_to_x86_64="yes"
      else
        errorExit "'$filename' was found but is not a valid ELF binary"
      fi
    else
      errorExit "couldn't find '$filename' either"
    fi
  fi
  if [ $x86_64 = "yes" ] && [ $x86 = "no" ]; then
    disable_x86="yes"
  fi
  if [ $disable_x86 = "yes" ] && [ $x86_64 = "no" ] ; then
    errorExit "x86 disabled but no x86_64 binary found"
  elif [ $disable_x86_64 = "yes" ] && [ $x86 = "no" ] ; then
    errorExit "x86_64 disabled but no x86 binary found"
  fi

  # copy source files
  echo "copy source files... "
  mkdir -p "$sourcedir"
  cp -vr "$origpath"/* "$sourcedir"
  echo "done"

  # remove executable bits
  find "$sourcedir" -type f -exec chmod a-x '{}' \;

  # remove executable stack
  export PATH="/usr/local/sbin:/usr/sbin:/sbin:${PATH}"  # on Debian /sbin isn't in PATH by default
  execstack="$(whereis -b execstack | awk '{print $2}')"
  if [ "x$execstack" != "x" ]; then
    find "$sourcedir" -name libmono.so -exec "$execstack" -c '{}' \;
  fi

  # delete unnecessary files
  for f in libCSteamworks.so libsteam_api.so libSteamworksNative.so SteamworksNative.dll \
           \*.dll.mdb Thumbs.db .DS_Store ;
  do
    find "$sourcedir" -name "$f" -delete
  done
  rm -rf `find "$sourcedir" -type d -name __MACOSX`

  # rename application
  name=$(echo "$name" | sed -e 's/\(.*\)/\L\1/; s/\ -\ /-/g; s/\ /-/g; s/_/-/g')
  [ "$filename" != "$name" ] && rename "s/$filename/$name/" "$sourcedir"/*
  if [ "$rename_to_x86" = "yes" ] && [ -f "$sourcedir/$name" ] ; then
    mv "$sourcedir/$name" "$sourcedir/${name}.x86"
    echo "application was renamed to ${name}.x86"
  elif [ "$rename_to_x86_64" = "yes" ] && [ -f "$sourcedir/$name" ] ; then
    mv "$sourcedir/$name" "$sourcedir/${name}.x86_64"
    echo "application was renamed to ${name}.x86_64"
  fi

  ScreenSelector="$sourcedir/${name}_Data/ScreenSelector"

  # convert ScreenSelector.bmp to ScreenSelector.png
  if [ -f "${ScreenSelector}.bmp" ] && [ ! -f "${ScreenSelector}.png" ] ; then
    convert "${ScreenSelector}.bmp" "${ScreenSelector}.png"
  fi

  # remove unused ScreenSelector.bmp
  rm -f "${ScreenSelector}.bmp"

  # add a ScreenSelector.png if required
  if [ -f "`find "$sourcedir" -name ScreenSelector.so | head -n1`" ] && \
     [ ! -f "${ScreenSelector}.png" ] ; then
    cp "$templates/ScreenSelector.png" "${ScreenSelector}.png"
  fi

  # icon
  default_icon="no"
  mkdir -p "$icondir"
  if [ -z "$icon" ] || [ ! -f "$icon" ] ; then
    if [ -f "$sourcedir/${name}_Data/Resources/UnityPlayer.png" ] ; then
      cp "$sourcedir/${name}_Data/Resources/UnityPlayer.png" "$icondir/$name.png"
      icon="$icondir/$name.png"
    else
      cp "$templates/icon.png" "$icondir/$name.png"
      icon="$icondir/$name.png"
      default_icon="yes"
    fi
    else
      cp "$icon" "$icondir/$name.png"
      icon="$icondir/$name.png"
  fi

  # enter packaging information
  echo ""
  if [ -z "$SHORTDESCRIPTION" ] ; then
    echo ""
    echo "Please enter a brief description,"
    read -p "i.e. 'Unity engine video game': " SHORTDESCRIPTION
  fi
  if [ -f "$PWD/description" ] ; then
    cp "$PWD/description" "$topsrc"
  else
    cp "$templates/description" "$topsrc"
    echo ""
    echo "Please add a more detailed description about the game in the text file"
    echo "$topsrc/description"
    echo "and press any key to continue."
    read -p "" -n1 -s
  fi
  sed -i 's/\r//' "$topsrc/description"  # dos2unix line endings
  echo "" >> "$topsrc/description"  # add a new line to the end of the file
  if [ -z "$VERSION" ] ; then
    echo ""
    echo "Enter the game's release version. It should begin with a number"
    read -p "and mustn't contain and spaces or underscores: " VERSION
  fi
  if [ -z "$MAINTAINER" ] ; then
    echo ""
    echo "Enter the package maintainer information."
    echo "Use the following pattern: John Doe <nick@domain.org>"
    read -p " " MAINTAINER
  fi
  if [ -z "$HOMEPAGE" ] ; then
    echo ""
    read -p "What's the game's homepage? " HOMEPAGE
  fi
  if [ -z "$YEAR" ] ; then
    echo ""
    read -p "What year is this game from? " YEAR
  fi
  if [ -z "$COPYRIGHT" ] ; then
    echo ""
    read -p "Who's holding the copyright? " COPYRIGHT
  fi
  echo ""
  echo ""
  [ -z "$SHORTDESCRIPTION" ] && SHORTDESCRIPTION="Unity engine video game"
  [ -z "$VERSION" ] && VERSION=$(date +%y.%m.%d.1)
  [ -z "$MAINTAINER" ] && MAINTAINER="John Doe <nick@domain.org>"
  [ -z "$HOMEPAGE" ] && HOMEPAGE="http://www.unity3d.com/"
  [ -z "$YEAR" ] && YEAR=$(date +%Y)
  [ -z "$COPYRIGHT" ] && COPYRIGHT="the creator(s) of '$UPSTREAMNAME'"

  # create Debian files
  mkdir -p "$builddir/x86"
  cp -r "$templates" "$debian"
  chmod a+x "$debian/rules" "$debian/make-icons.sh"

  cat >> "$builddir/x86/${name}.desktop" << EOF
[Desktop Entry]
Name=$UPSTREAMNAME
Comment=$SHORTDESCRIPTION
Exec=$name
Type=Application
Categories=Game;
StartupNotify=true
Icon=$name
EOF

  echo "debian/${name}.6" > "$builddir/x86/debian/${name}.manpages"

  cat >> "$builddir/x86/debian/${name}.6" << EOF
.TH ${name^^} 6 "" "$(date +%d.%m.%Y)"
.SH NAME
$name \- $SHORTDESCRIPTION
.SH SYNOPSIS
.B $name
.SH OPTIONS
This game has no command line options.
.SH DESCRIPTION
EOF
  fold -s "$topsrc/description" >> "$builddir/x86/debian/${name}.6"
  cat >> "$builddir/x86/debian/${name}.6" << EOF
.SH SEE ALSO
.I $HOMEPAGE
.SH AUTHOR
$COPYRIGHT
EOF

  cat >> "$debian/copyright" << EOF
Format: http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: $UPSTREAMNAME
Source: $HOMEPAGE

Files: *
Copyright: 2012-2016 Unity Technologies
           $YEAR $COPYRIGHT
EOF
  cat "$templates/copyright.in" >> "$debian/copyright"

  [ $datapackage = "yes" ] && datadeps=", ${name}-data (= \${binary:Version})"
  printf '%s\n' "`cat "$topsrc/description"`" | fold -s -w 79 | sed 's/^/ /g; s/^ $/ ./g; s/ $//g' > "$topsrc/description_processed"
  cat >> "$debian/control.in" << EOF
Source: $name
Section: games
Priority: optional
Maintainer: $MAINTAINER
Build-Depends: debhelper (>= 9)
Standards-Version: 3.9.5
Homepage: $HOMEPAGE

Package: $name
Architecture: any
Depends: \${misc:Depends}, \${shlibs:Depends}, libpulse0$datadeps
Description: $SHORTDESCRIPTION
EOF
  cat "$topsrc/description_processed" >> "$debian/control.in"

  if [ $datapackage = "yes" ] ; then
    cat >> "$debian/control.in" << EOF

Package: ${name}-data
Architecture: all
Depends: \${misc:Depends}
Recommends: $name
Description: $SHORTDESCRIPTION - game data
EOF
    cat "$topsrc/description_processed" >> "$debian/control.in"
    echo " ." >> "$debian/control.in"
    echo " This package installs the $name game data." >> "$debian/control.in"
  fi

  uniq "$debian/control.in" "$debian/control"

  cat >> "$debian/changelog" << EOF
$name ($VERSION) unstable; urgency=medium

  * Initial release
 
 -- $MAINTAINER  $(date -R)
EOF

  if [ $x86_64 = "yes" ] ; then
    mkdir -p "$builddir/x86_64/debian"
    cp -rf "$debian"/* "$builddir/x86_64/debian"
    cp -f "$builddir/x86/${name}.desktop" "$builddir/x86_64"
    cat >> "$builddir/x86_64/debian/confflags" << EOF
NAME = $name
ICON = "$icon"
ARCH = x86_64
DATAPACKAGE = $datapackage
Z = $compression
PATCHELF = $patchelf
EOF
  fi
  cat >> "$debian/confflags" << EOF
NAME = $name
ICON = "$icon"
ARCH = x86
DATAPACKAGE = $datapackage
Z = $compression
PATCHELF = $patchelf
EOF

  [ $disable_x86 = "yes" ] && rm -rf "$builddir/x86"
  [ $disable_x86_64 = "yes" ] && rm -rf "$builddir/x86_64"
  if [ -d "$builddir/x86" ] ; then
    echo "hard link files to build/x86... "
    mkdir -p "$builddir/x86/source"
    cp -vrl "$sourcedir/${name}_Data" "$sourcedir/${name}.x86" "$builddir/x86/source"
    echo "done"
  fi
  if [ -d "$builddir/x86_64" ] ; then
    echo "hard link files to build/x86_64..."
    mkdir -p "$builddir/x86_64/source"
    cp -vrl "$sourcedir/${name}_Data" "$sourcedir/${name}.x86_64" "$builddir/x86_64/source"
    echo "done"
  fi
  if [ -d "$builddir/x86" ] && [ -d "$builddir/x86_64" ] ; then
    echo "arch_only = --arch" >> "$builddir/x86_64/debian/confflags"
  fi

  cat <<EOL

                   >> Summary <<
                    name: $UPSTREAMNAME
application/package name: $name
             description: $SHORTDESCRIPTION
         package version: $VERSION
       packagemaintainer: $MAINTAINER
                homepage: $HOMEPAGE
                    year: $YEAR
               copyright: $COPYRIGHT

       build datapackage? $datapackage
      compression method: $compression
             disable x86? $disable_x86
          disable x86_64? $disable_x86_64
            use patchelf? $patchelf

    detailed description:
$(cat "$topsrc/description_processed")


The files are prepared. Run '$appname build' to build Debian packages.
Or modify the the files in '$builddir' first.
EOL

  exit 0
fi


################## build ##################
buildpackage () {
  arch=${1}
  if [ -d "$builddir/${arch}" ] ; then
    name="$(grep 'NAME = ' $builddir/${arch}/debian/confflags | sed -e 's/NAME = //')"
    cd "$builddir/${arch}"
    chmod a+x debian/rules source/${name}.${arch}
    mv source/${name}.${arch} source/${name}
    test ${arch} = "x86" && purge=x86_64 || purge=x86
    rm -rf source/${name}_Data/Mono/${purge} source/${name}_Data/Plugins/${purge} source/${name}.${purge}
    dpkg-buildpackage -b -us -uc 2>&1 | tee "$builddir/${arch}-build.log"
  fi
}

if [ $mode = "build" ] ; then
  if [ ! -d "$builddir/x86" ] && [ ! -d "$builddir/x86_64" ] ; then
    echo "no files in '$builddir'!"
    errorExit "run '$appname prepare <path>' first"
  fi

  buildpackage x86
  buildpackage x86_64

  cd "$builddir"
  echo ""
  ls *.deb >/dev/null
  if [ $(echo $?) = 0 ] ; then
    for f in *.deb ; do
      echo "$f:"
      dpkg-deb -I $f
      lintian $f
      echo ""
    done 2>&1 | tee "$builddir/packages.log"
    for f in *.deb ; do
      echo "$f:"
      dpkg-deb -c $f
      echo ""
    done 2>&1 | tee -a "$builddir/packages.log"
  fi
  cp -f *.deb "$output"
  echo "Debian packages have been copied to '$output'"
fi

exit 0
